### PR TITLE
Dubbing access

### PR DESCRIPTION
**Pull request by austinbhale**
Thank you for this project! I added in some dubbing functionality, since it's been [launched for all price tiers in May](https://elevenlabs.io/docs/api-reference/how-to-dub-a-video)

- feat: dubbing access; upload, asynchronous partial download, & transcriptions
- feat: dubbing unit test on the sample audio file. confirmed for videos too, you just might need to enable the watermark depending on your price tier
- refactor: upgrade to net8.0
- refactor: treat warnings as errors set to false for sharing with other people's setups

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Thanks @austinbhale! I'll check it out shortly. 

Only initial feedback is to revert back to .net6. I wanted to keep support for that until it reaches EOL

**Comment by StephenHodgson** [comment]
Also please check your tab settings. Should be 4 spaces.

**Comment by StephenHodgson** [comment]
Please revert all changes to .csproj files

**Comment by austinbhale** [comment]
> Please revert all changes to .csproj files

Could we keep the added net8.0 framework though? I can revert the treat warnings as errors as well

**Comment by StephenHodgson** [comment]
> Could we keep the added net8.0 framework though?

It will automatically be supported with net6.0 reference.

**Comment by austinbhale** [comment]
I gotcha, keeping it compatible for net8.0 like that sounds good. Just wanted to take advantage of perf updates to the CLR, but prob no noticeable difference here

**Comment by austinbhale** [comment]
One more thing is I'll make a test for an online URL since that's supposed to work too

**Comment by austinbhale** [comment]
Ok it works for online content too! I should be done making changes until your testing & review :) Feel free to edit anything & swap out the YouTube video, I just chose theirs randomly

**Comment by StephenHodgson** [comment]
looks great. My only real Change Request is to make any return types from `StartDubbingAsync` a defined object

**Comment by austinbhale** [comment]
Thanks for the suggestion! I think that looks much cleaner for deserialization too

**Comment by austinbhale** [comment]
Hi! Any updates on integrating this?

**Comment by StephenHodgson** [comment]
Sorry been a bit busy. Working on some other edits as well but got overloaded with work. 

Overall looks good and I'll get this in as soon as I finish up adding the other endpoints for sfx

**Comment by austinbhale** [comment]
Awesome, looking forward to trying those out. No rush, can use a private NuGet till then. Thanks!

**Review by StephenHodgson — APPROVED** [review]

**Comment by StephenHodgson** [comment]
@austinbhale You didn't give me edit access to your PR so I wasn't able to sync it with development, so I merged it into a new branch and opened a new PR #50

**Pull request closed without merging**
